# Role for each user type in each namespace
{{- range $namespace := list "staging" "production" }}
  {{- range $userName := list "developer" "admin" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ $namespace }}
  name: {{ $userName }}-role
rules:
  {{- if and (eq $userName "developer") (eq $namespace "production") }}
  # Developer has no access in the production namespace, so no rules are defined
  {{- else }}
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "delete"
  {{ end }}
---
  {{ end }}
{{ end }}

# RoleBindings
{{- range $namespace := list "staging" "production" }}
  {{- range $userName := list "developer" "admin" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ $namespace }}
  name: {{ $userName }}-role-binding
subjects:
  - kind: User
    name: {{ $userName }}
roleRef:
  kind: Role
  name: {{ $userName }}-role
  apiGroup: rbac.authorization.k8s.io
---
  {{ end }}
{{ end }}
