apiVersion: v1
kind: Secret
metadata:
  name: staging-rds-credentials
  namespace: staging
type: Opaque
data:
  username: {{ .Values.rdsUsernameStaging | b64enc }}
  password: {{ .Values.rdsPasswordStaging | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: production-rds-credentials
  namespace: production
type: Opaque
data:
  username: {{ .Values.rdsUsernameProd | b64enc }}
  password: {{ .Values.rdsPasswordProd | b64enc }}
